services:
  # snmptrapd:
  #   container_name: snmptrapd
  #   build:
  #     context: ./snmptrapd
  #   image: snmptrapd:latest
  #   ports:
  #     - 127.0.0.1:9116:162/udp
  #   volumes:
  #     - snmptrapd/config:/etc/snmp/:ro

  telegraf-trapd-syslog:
    container_name: telegraf-trapd-syslog
    image: docker.mirror.markant.com/telegraf:latest
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./mibs:/usr/share/snmp/mibs:ro
    networks:
      - ext-network
    ports:
      - 127.0.0.1:9116:9116/udp
  grafana-alloy-syslogrcv:
    container_name: grafana-alloy-syslogrcv
    image: docker.mirror.markant.com/grafana/alloy:latest
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro
    ports: 
      - 127.0.0.1:12345:12345
    networks:
      - ext-network
    command: [
      "run",
      "--server.http.listen-addr=0.0.0.0:12345",
      "--storage.path=/var/lib/alloy/data",
#      "--stability.level=experimental",
      "/etc/alloy/config.alloy",
      ]
    env_file: ./.env
  loki:
    image: grafana/loki:latest
    #ports:
    #  - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - ext-network
  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - ext-network

networks:
  int-network:
    internal: true
  ext-network:
    internal: false
